#! /bin/bash

set -e
set -o pipefail

#If the config directory (.mkscript) is not found.
if [ ! -e ~/.mkscript ]; then
	mkdir ~/.mkscript
	touch template.txt.
	echo -e "#! /bin/bash\n\nset -u\nset -e\nset -o pipefail" >> ~/.mkscript/template.txt

	echo "First run, config directory created at ~/.mkscript."
	echo "Find and edit file templetes there."
fi

#If the command was run with no parameters.
if [ -z "$1" ]; then
	echo "No filename specified."
	exit
fi

#If an absolute path is given as the parameter, checks to see if the first character is a /.
if [[ ${1:0:1} == "/" ]]; then
	destination=$1

#If a relative path is given as the parameter.
else
        destination=$(pwd)$"/"$1
fi

#If the file already exists.
if [ -e "$destination" ]; then

	echo "The file already exists."
	exit
fi

#Create the script, make it executeable, apply the template, and open it in nano.
touch "$destination"

chmod +x "$destination"

cat ~/.mkscript/template.txt > "$destination"

nano "$destination"
