#! /bin/bash

#Instructions
#In this exercise, you will need to write a function called ENGLISH_CALC which can process sentences such as:
#'3 plus 5', '5 minus 1' or '4 times 6' and print the results as: '3 + 5 = 8', '5 - 1 = 4' or '4 * 6 = 24' respectively.

# enter your function code here
#Creating the function.
function ENGLISH_CALC {
	#A case for each operator. Taking in the textual operator and assigning its symbolic equivalent to $operator.
	case "$2" in
	    	plus) operator="+";;
		minus) operator="-";;
	    	times) operator="*";;
    		dividedBy) operator="/";;
	esac

	#Calculatingthe answer to the problem.
	answer=$(($1 $operator $3))

	#Printing out the answer an the symbolic equation.
	echo "$1 $operator $3 = $answer"
}

# testing code
ENGLISH_CALC 3 plus 5
ENGLISH_CALC 5 minus 1
ENGLISH_CALC 4 times 6
