#! /bin/bash

#INSTRUCTIONS:
#The target of this exercise is to create a string, an integer, and a complex variable using command substitution.
#The string should be named BIRTHDATE and should contain the text "Jan 1, 2000".
#The integer should be named Presents and should contain the number 10.
#The complex variable should be named BIRTHDAY and should contain the full weekday name of the day matching the date in variable BIRTHDATE e.g. Saturday.
#Note that the 'date' command can be used to convert a date format into a different date format.
#For example, to convert date value, $date1, to day of the week of date1, use:

#Settings all of the variables to be used in the script.

#Setting the BIRTHDATE, using quotes "" so that it can have spaces.
BIRTHDATE="Jan 1, 2000"
#Setting the number of Presents, no quotes needed because it is an int.
Presents=10
#Setting the BIRTHDATE by capturing the output of a command using double-ticks
BIRTHDAY=`date -d "$BIRTHDATE" +%A`

# Code below should be ignored; the subjects have not been covered yet.

if [ "$BIRTHDATE" == "Jan 1, 2000" ] ; then
    echo "BIRTHDATE is correct, it is $BIRTHDATE"
else
    echo "BIRTHDATE is incorrect - please retry"
fi
if [ $Presents == 10 ] ; then
    echo "I have received $Presents presents"
else
    echo "Presents is incorrect - please retry"
fi
if [ "$BIRTHDAY" == "Saturday" ] ; then
    echo "I was born on a $BIRTHDAY"
else
    echo "BIRTHDAY is incorrect - please retry"
fi
